export const SHOE_API = [
  {
    id: 1,
    name: "Pellé Classic Oxford",
    image: "/images/classic-shoe.png",
    price: 129.99,
  },
  {
    id: 2,
    name: "Midnight Loafer",
    image: "/images/shoe-with-gaps.png",
    price: 119.99,
  },
  {
    id: 3,
    name: "Sienna Chelsea Boot",
    image: "/images/Sienna-Chelsea-Boot.png",
    price: 139.99,
  },
  {
    id: 4,
    name: "Matte Black Loafer",
    image: "/images/Matte-Black-Derby.png",
    price: 124.99,
  },
  { id: 5, name: "Rust Suede Sandal", image: "/images/red.png", price: 99.99 },
  {
    id: 6,
    name: "Heritage Brogue Loafer",
    image: "/images/with-gaps2.png",
    price: 134.99,
  },
  {
    id: 7,
    name: "Shadow Monk Strap",
    image: "/images/classic2.png",
    price: 144.99,
  },
  {
    id: 8,
    name: "Ivory Minimal Sneaker",
    image: "/images/sneaker.png",
    price: 89.99,
  },
  {
    id: 9,
    name: "Espresso Penny Sneaker",
    image: "/images/women.png",
    price: 119.49,
  },
  {
    id: 10,
    name: "Canvas City Loafer",
    image: "/images/sneaker2.png",
    price: 84.99,
  },
  {
    id: 11,
    name: "Olive Desert Loafer",
    image: "/images/longone.png",
    price: 109.99,
  },
  {
    id: 12,
    name: "Walnut Wingtip Loafer",
    image: "/images/shakalad.png",
    price: 139.99,
  },
  {
    id: 13,
    name: "Charcoal Chukka Boot",
    image: "/images/sneaker3.png",
    price: 102.99,
  },
  {
    id: 14,
    name: "Forest Slip-On Loafer",
    image: "/images/similartomine.png",
    price: 95.99,
  },
  {
    id: 15,
    name: "Luxe Court Sneaker",
    image: "/images/whiteone.png",
    price: 124.49,
  },
  {
    id: 16,
    name: "Almond Cap Toe",
    image: "/images/whiteunder.png",
    price: 129.49,
  },
  {
    id: 17,
    name: "Tan Sport Sneaker",
    image: "/images/tan-sport-sneaker.png",
    price: 129.99,
  },
  {
    id: 18,
    name: "Beige Retro Sneaker",
    image: "/images/beige-retro-sneaker.png",
    price: 119.99,
  },
  {
    id: 19,
    name: "Gray Mesh Runner",
    image: "/images/gray-mesh-runner.png",
    price: 134.99,
  },
  {
    id: 20,
    name: "Navy Leather Sneaker",
    image: "/images/navy-leather-sneaker.png",
    price: 124.99,
  },
  {
    id: 21,
    name: "Cognac Casual Slip-On",
    image: "/images/cognac-slip-on.png",
    price: 99.99,
  },
  {
    id: 22,
    name: "Taupe Trail Runner",
    image: "/images/taupe-trail-runner.png",
    price: 114.99,
  },
  {
    id: 23,
    name: "Black Slide Sandal",
    image: "/images/black-slide.png",
    price: 89.99,
  },
  {
    id: 24,
    name: "Green Signature Sandal",
    image: "/images/green-slide.png",
    price: 84.99,
  },
  {
    id: 25,
    name: "Brown Open-Back Sandal",
    image: "/images/brown-mule.png",
    price: 119.49,
  },
  {
    id: 26,
    name: "Slim Tan Sandal",
    image: "/images/slim-tan-slide.png",
    price: 94.99,
  },
  {
    id: 27,
    name: "Classic Cross Sandal",
    image: "/images/cross-sandal.png",
    price: 104.99,
  },
  {
    id: 28,
    name: "Classic Tan Loafer",
    image: "/images/classic-tan-loafer.png",
    price: 124.99,
  },
  {
    id: 29,
    name: "Navy Suede Loafer",
    image: "/images/navy-suede-loafer.png",
    price: 114.99,
  },
  {
    id: 30,
    name: "Olive Driving Loafer",
    image: "/images/olive-driving-loafer.png",
    price: 109.99,
  },
  {
    id: 31,
    name: "Black Leather Loafer",
    image: "/images/black-leather-loafer.png",
    price: 119.99,
  },
  {
    id: 32,
    name: "Ivory Penny Loafer",
    image: "/images/ivory-penny-loafer.png",
    price: 109.49,
  },
  {
    id: 33,
    name: "Woven Brown Loafer",
    image: "/images/woven-brown-moccasin.png",
    price: 114.99,
  },
];

export const WOMEN_SHOE_API = [
  {
    id: 1,
    name: "Women's pink suede sneaker",
    image: "/images/women-pink-suede.png",
    price: 620,
  },
  {
    id: 2,
    name: "Women's red suede sneaker",
    image: "/images/women-red-suede.png",
    price: 620,
  },
  {
    id: 3,
    name: "Women's natural suede sneaker",
    image: "/images/women-natural-suede.png",
    price: 620,
  },
  {
    id: 4,
    name: "Women's white tumbled leather sneaker",
    image: "/images/women-white-tumbled.png",
    price: 550,
  },
  {
    id: 5,
    name: "Women's silver laminated leather DBS Oly sneaker",
    image: "/images/women-silver-dbs.png",
    price: 750,
  },
  {
    id: 6,
    name: "Women's white, beige and silver leather and suede DBS Oly sneaker",
    image: "/images/women-white-beige-silver-dbs.png",
    price: 590,
  },
  {
    id: 7,
    name: "Women's white tumbled leather DBS Oly sneaker",
    image: "/images/women-white-dbs.png",
    price: 590,
  },
  {
    id: 8,
    name: "Women's white and violet leather and suede DBS Oly sneaker",
    image: "/images/women-white-violet-dbs.png",
    price: 590,
  },
  {
    id: 9,
    name: "Women's pink tumbled leather slip-on sneaker",
    image: "/images/women-pink-slipon.png",
    price: 650,
  },
  {
    id: 10,
    name: "Women's white tumbled leather slip-on sneaker",
    image: "/images/women-white-slipon.png",
    price: 650,
  },
  {
    id: 11,
    name: "Women's silver laminated leather slip-on sneaker",
    image: "/images/women-silver-slipon.png",
    price: 650,
  },
  {
    id: 12,
    name: "Women's white, blue and red leather and suede DBS Oly sneaker",
    image: "/images/women-white-blue-red-dbs.png",
    price: 590,
  },
  {
    id: 13,
    name: "Women's silver laminated leather DBS Oly sneaker",
    image: "/images/women-silver2-dbs.png",
    price: 413,
  },

  {
    id: 15,
    name: "Women's black leather sneaker",
    image: "/images/women-black-leather.png",
    price: 550,
  },
  {
    id: 16,
    name: "Women's orange tumbled leather sneaker",
    image: "/images/women-orange-leather.png",
    price: 550,
  },
  {
    id: 17,
    name: "Women's pink tumbled leather slip-on sneaker",
    image: "/images/women-pink2-slipon.png",
    price: 650,
  },
  {
    id: 18,
    name: "Women's pink suede slip-on sneaker",
    image: "/images/women-pink-suede-slipon.png",
    price: 650,
  },
  {
    id: 19,
    name: "Women's gold laminated leather and crystals high-heel sandal",
    image: "/images/women-gold-highheel.png",
    price: 850,
  },
  {
    id: 20,
    name: "Women's silver laminated leather and crystals high-heel sandal",
    image: "/images/women-silver-highheel.png",
    price: 850,
  },
  {
    id: 21,
    name: "Women's silver laminated leather and crystals sandal",
    image: "/images/women-silver-flat.png",
    price: 790,
  },
  {
    id: 22,
    name: "Women's gold laminated leather and crystals sandal",
    image: "/images/women-gold-flat.png",
    price: 790,
  },
  {
    id: 23,
    name: "Women's black leather mid-heel sandal",
    image: "/images/women-black-midheel.png",
    price: 690,
  },
  {
    id: 24,
    name: "Women's black leather high-heel sandal",
    image: "/images/women-black-highheel.png",
    price: 413,
  },
  {
    id: 25,
    name: "Women's red leather high-heel sandal",
    image: "/images/women-red-highheel.png",
    price: 455,
  },
  {
    id: 26,
    name: "Women's black leather high-heel sandal",
    image: "/images/women-black2-highheel.png",
    price: 455,
  },
  {
    id: 27,
    name: "Women's orange woven leather double-buckle Didi slide sandal",
    image: "/images/women-orange-didi.png",
    price: 650,
  },
  {
    id: 28,
    name: "Women's beige woven leather double-buckle slide sandal",
    image: "/images/women-beige-didi.png",
    price: 650,
  },
  {
    id: 29,
    name: "Women's white leather double-buckle Didi slide sandal",
    image: "/images/women-white-didi.png",
    price: 590,
  },
  {
    id: 30,
    name: "Women's brown tumbled leather double-buckle Didi slide sandal",
    image: "/images/women-brown-didi.png",
    price: 590,
  },
  {
    id: 31,
    name: "Women's black suede loafer",
    image: "/images/women-black-loafer.png",
    price: 590,
  },
  {
    id: 32,
    name: "Women's dark brown suede loafer",
    image: "/images/women-darkbrown-loafer.png",
    price: 690,
  },
  {
    id: 33,
    name: "Women's red suede loafer",
    image: "/images/women-red-loafer.png",
    price: 690,
  },
  {
    id: 34,
    name: "Women's light brown leather Carla loafer",
    image: "/images/women-carla-brown.png",
    price: 790,
  },
  {
    id: 35,
    name: "Women's gold laminated leather Carla loafer",
    image: "/images/women-carla-gold.png",
    price: 790,
  },
  {
    id: 36,
    name: "Women's light brown leather penny loafer",
    image: "/images/women-penny-lightbrown.png",
    price: 690,
  },
  {
    id: 37,
    name: "Women's black leather penny loafer",
    image: "/images/women-penny-black.png",
    price: 690,
  },
  {
    id: 38,
    name: "Women's beige tumbled leather penny loafer",
    image: "/images/women-penny-beige.png",
    price: 690,
  },
  {
    id: 39,
    name: "Women's white tumbled leather penny loafer",
    image: "/images/women-penny-white.png",
    price: 690,
  },
  {
    id: 40,
    name: "Women's light blue suede loafer",
    image: "/images/women-loafer-lightblue.png",
    price: 413,
  },
  {
    id: 41,
    name: "Women's red suede loafer",
    image: "/images/women-loafer-red.png",
    price: 590,
  },
  {
    id: 42,
    name: "Women's dark brown suede penny loafer",
    image: "/images/women-penny-darkbrown.png",
    price: 690,
  },
  {
    id: 43,
    name: "Women's polished black leather penny loafer",
    image: "/images/women-penny-polishedblack.png",
    price: 690,
  },
  {
    id: 44,
    name: "Women's brown leather penny loafer",
    image: "/images/women-penny-brown.png",
    price: 690,
  },
  {
    id: 45,
    name: "Women's black leather Andrea tassel loafer",
    image: "/images/women-andrea-black.png",
    price: 690,
  },
  {
    id: 46,
    name: "Women's black patent leather Andrea tassel loafer",
    image: "/images/women-andrea-patentblack.png",
    price: 690,
  },
  {
    id: 47,
    name: "Women's pink suede loafer",
    image: "/images/women-loafer-pink1.png",
    price: 590,
  },
  {
    id: 48,
    name: "Women's pink suede loafer",
    image: "/images/women-loafer-pink2.png",
    price: 650,
  },
  {
    id: 49,
    name: "Women's beige suede loafer",
    image: "/images/women-loafer-beige.png",
    price: 650,
  },
];
