export const SHOE_API = [
    { "id": 1, "name": "Pellé Classic Oxford", "image": "/images/classic-shoe.png", "price": 129.99 },
    { "id": 2, "name": "Midnight Loafer", "image": "/images/shoe-with-gaps.png", "price": 119.99 },
    { "id": 3, "name": "Sienna Chelsea Boot", "image": "/images/Sienna-Chelsea-Boot.png", "price": 139.99 },
    { "id": 4, "name": "Matte Black Loafer", "image": "/images/Matte-Black-Derby.png", "price": 124.99 },
    { "id": 5, "name": "Rust Suede Sandal", "image": "/images/red.png", "price": 99.99 },
    { "id": 6, "name": "Heritage Brogue Loafer", "image": "/images/with-gaps2.png", "price": 134.99 },
    { "id": 7, "name": "Shadow Monk Strap", "image": "/images/classic2.png", "price": 144.99 },
    { "id": 8, "name": "Ivory Minimal Sneaker", "image": "/images/sneaker.png", "price": 89.99 },
    { "id": 9, "name": "Espresso Penny Sneaker", "image": "/images/women.png", "price": 119.49 },
    { "id": 10, "name": "Canvas City Loafer", "image": "/images/sneaker2.png", "price": 84.99 },
    { "id": 11, "name": "Olive Desert Loafer", "image": "/images/longone.png", "price": 109.99 },
    { "id": 12, "name": "Walnut Wingtip Loafer", "image": "/images/shakalad.png", "price": 139.99 },
    { "id": 13, "name": "Charcoal Chukka Boot", "image": "/images/sneaker3.png", "price": 102.99 },
    { "id": 14, "name": "Forest Slip-On Loafer", "image": "/images/similartomine.png", "price": 95.99 },
    { "id": 15, "name": "Luxe Court Sneaker", "image": "/images/whiteone.png", "price": 124.49 },
    { "id": 16, "name": "Almond Cap Toe", "image": "/images/whiteunder.png", "price": 129.49 },
    { "id": 17, "name": "Tan Sport Sneaker", "image": "/images/tan-sport-sneaker.png", "price": 129.99 },
    { "id": 18, "name": "Beige Retro Sneaker", "image": "/images/beige-retro-sneaker.png", "price": 119.99 },
    { "id": 19, "name": "Gray Mesh Runner", "image": "/images/gray-mesh-runner.png", "price": 134.99 },
    { "id": 20, "name": "Navy Leather Sneaker", "image": "/images/navy-leather-sneaker.png", "price": 124.99 },
    { "id": 21, "name": "Cognac Casual Slip-On", "image": "/images/cognac-slip-on.png", "price": 99.99 },
    { "id": 22, "name": "Taupe Trail Runner", "image": "/images/taupe-trail-runner.png", "price": 114.99 },
    { "id": 23, "name": "Black Slide Sandal", "image": "/images/black-slide.png", "price": 89.99 },
    { "id": 24, "name": "Green Signature Sandal", "image": "/images/green-slide.png", "price": 84.99 },
    { "id": 25, "name": "Brown Open-Back Sandal", "image": "/images/brown-mule.png", "price": 119.49 },
    { "id": 26, "name": "Slim Tan Sandal", "image": "/images/slim-tan-slide.png", "price": 94.99 },
    { "id": 27, "name": "Classic Cross Sandal", "image": "/images/cross-sandal.png", "price": 104.99 },
    { "id": 28, "name": "Classic Tan Loafer", "image": "/images/classic-tan-loafer.png", "price": 124.99 },
    { "id": 29, "name": "Navy Suede Loafer", "image": "/images/navy-suede-loafer.png", "price": 114.99 },
    { "id": 30, "name": "Olive Driving Loafer", "image": "/images/olive-driving-loafer.png", "price": 109.99 },
    { "id": 31, "name": "Black Leather Loafer", "image": "/images/black-leather-loafer.png", "price": 119.99 },
    { "id": 32, "name": "Ivory Penny Loafer", "image": "/images/ivory-penny-loafer.png", "price": 109.49 },
    { "id": 33, "name": "Woven Brown Loafer", "image": "/images/woven-brown-moccasin.png", "price": 114.99 },
];

